### ISSUE TITLE
解决 Okhttp java.io.EOFException: \n not found: size=0 content= unexpected end

### ISSUE THREAD

**Issue by DreamUniverse843** [YggdrasilOfficialProxy/YggdrasilOfficialProxy#10]
**我已确认我使用的版本是收到支持的v2.x**

**我已经确认出现服务器宕机等无法进入服务器的情况时 https://status.mojang.com/check 显示正常 且 YOP 代理配置无误**

错误说明:
BC服务端不能一次就正确区分用户的来源是正版还是外置
下方便是运行实例（我的是外置账户 但是proxy判断并不准确 反复重连才成功）

错误复现步骤:
1. 打开cmd
2.BC端进行用户登录 正版的和外置的都不能一次进入 都需要Proxy自行判断多次才能进入 
尝试期间提示无法连接认证服务器 正版和外置均如此

错误日志:
```
20:52:24 [INFO] [/客户端登录IP地址] <-> InitialHandler has connected
20:52:25 [SEVERE] Error authenticating DreamUniverse with minecraft.net
java.lang.IllegalStateException: Expected HTTP response 200 OK, got 500 Internal Server Error
	at net.md_5.bungee.http.HttpHandler.channelRead0(HttpHandler.java:49)
	at net.md_5.bungee.http.HttpHandler.channelRead0(HttpHandler.java:14)
	at io.netty.channel.SimpleChannelInboundHandler.channelRead(SimpleChannelInboundHandler.java:99)
	at io.netty.channel.AbstractChannelHandlerContext.invokeChannelRead(AbstractChannelHandlerContext.java:379)
	at io.netty.channel.AbstractChannelHandlerContext.invokeChannelRead(AbstractChannelHandlerContext.java:365)
	at io.netty.channel.AbstractChannelHandlerContext.fireChannelRead(AbstractChannelHandlerContext.java:357)
	at io.netty.channel.CombinedChannelDuplexHandler$DelegatingChannelHandlerContext.fireChannelRead(CombinedChannelDuplexHandler.java:436)
	at io.netty.handler.codec.ByteToMessageDecoder.fireChannelRead(ByteToMessageDecoder.java:324)
	at io.netty.handler.codec.ByteToMessageDecoder.channelRead(ByteToMessageDecoder.java:296)
	at io.netty.channel.CombinedChannelDuplexHandler.channelRead(CombinedChannelDuplexHandler.java:251)
	at io.netty.channel.AbstractChannelHandlerContext.invokeChannelRead(AbstractChannelHandlerContext.java:379)
	at io.netty.channel.AbstractChannelHandlerContext.invokeChannelRead(AbstractChannelHandlerContext.java:365)
	at io.netty.channel.AbstractChannelHandlerContext.fireChannelRead(AbstractChannelHandlerContext.java:357)
	at io.netty.handler.timeout.IdleStateHandler.channelRead(IdleStateHandler.java:286)
	at io.netty.channel.AbstractChannelHandlerContext.invokeChannelRead(AbstractChannelHandlerContext.java:379)
	at io.netty.channel.AbstractChannelHandlerContext.invokeChannelRead(AbstractChannelHandlerContext.java:365)
	at io.netty.channel.AbstractChannelHandlerContext.fireChannelRead(AbstractChannelHandlerContext.java:357)
	at io.netty.channel.DefaultChannelPipeline$HeadContext.channelRead(DefaultChannelPipeline.java:1410)
	at io.netty.channel.AbstractChannelHandlerContext.invokeChannelRead(AbstractChannelHandlerContext.java:379)
	at io.netty.channel.AbstractChannelHandlerContext.invokeChannelRead(AbstractChannelHandlerContext.java:365)
	at io.netty.channel.DefaultChannelPipeline.fireChannelRead(DefaultChannelPipeline.java:919)
	at io.netty.channel.epoll.AbstractEpollStreamChannel$EpollStreamUnsafe.epollInReady(AbstractEpollStreamChannel.java:792)
	at io.netty.channel.epoll.EpollEventLoop.processReady(EpollEventLoop.java:475)
	at io.netty.channel.epoll.EpollEventLoop.run(EpollEventLoop.java:378)
	at io.netty.util.concurrent.SingleThreadEventExecutor$4.run(SingleThreadEventExecutor.java:989)
	at io.netty.util.internal.ThreadExecutorMap$2.run(ThreadExecutorMap.java:74)
	at java.lang.Thread.run(Thread.java:748)
20:52:29 [INFO] [/IP地址] <-> InitialHandler has connected
20:52:34 [INFO] [/IP地址] <-> InitialHandler has connected
20:52:35 [INFO] [DreamUniverse] <-> ServerConnector [主城] has connected
```
反复多次才登录成功 很不方便 玩家还误以为外置或者正版垮掉了

YggdrasilOfficialProxy配置
```
# API Root, 将这里改成原来的 API Root！
API地址隐藏处理
# Authlib Injector的位置, 无效的话服务器将无法启动
authlib-injector="authlib-injector.jar"
# 重要! 重要!, 必须为 true!
edited=true
# 在合并玩家查找的时候, 是否优先使用正版服务器的内容
official-first=false
# 代理服务器的设置
server {
    # 换成 127.0.0.1
    host="127.0.0.1"
    # 随便写, 随便写一个没有被占用的端口
    port=45342
}
# Proxy settings
proxy {
    just-example-for-http {
        type=http
        url="http://localhost/proxy"
    }
    # The proxy of official connecting
    official {
        host=localhost
        port=1080
        type=direct
    }
    # The proxy of yggdrasil connecting
    yggdrasil {
        type=direct
    }
}
```
服务器启动命令行
```
java -server -Xincgc -javaagent:YggdrasilOfficialProxy.jar -Xss512K -XX:+AggressiveOpts -XX:+UseCompressedOops -XX:+UseCMSCompactAtFullCollection -XX:+UseFastAccessorMethods -XX:ParallelGCThreads=4 -XX:+UseConcMarkSweepGC -XX:CMSFullGCsBeforeCompaction=2 -XX:CMSInitiatingOccupancyFraction=70 -XX:-DisableExplicitGC -XX:-DisableExplicitGC -XX:TargetSurvivorRatio=90
```

**Comment by Karlatemp** [comment]
已找到一处隐藏错误，但是该错误的发生需要正版和外置服务器全部无数据返回的时候才会发生，请问您**真的确定**第三方登录服务器没有宕机吗

**Comment by DreamUniverse843** [comment]
我确定的 外置服务器真的没有宕机 外置是我自己的

**Comment by Karlatemp** [comment]
使用默认[yggdrasil server](https://skin.prinzeugen.net)无法复现，只能断定为你自己的外置服务器的问题

**Comment by DreamUniverse843** [comment]
刚才重试了纯authlib-injector 没有问题

**Comment by DreamUniverse843** [comment]
外置地址https://skin.shiyeziya.world/api/yggdrasil

**Comment by DreamUniverse843** [comment]
外置服务器有高防 可以试一下https://skin.shiyeziya.world/api/yggdrasil

**Comment by Karlatemp** [comment]
初步定位原因是, 你的服务器返回的Http Header头不被okhttp认可
