### ISSUE TITLE
[PROBLEM]服务器每隔一段时间会刷报错

### ISSUE THREAD

**Issue by Huaxidesu** [YggdrasilOfficialProxy/YggdrasilOfficialProxy#23]
Ygg版本2.1.3-2.3.0都会出现（以前使用bc端没有）
服务端为[catserver](https://github.com/Luohuayu/CatServer)
ygg配置为https://github.com/YggdrasilOfficialProxy/YggdrasilOfficialProxy/files/6565753/YggdrasilOfficialProxy.txt
报错文本
`[20:04:47] [eventLoopGroupProxy-4-1/INFO] []: [YggdrasilOfficialProxy] [ERROR] Unhandled: POST - /api/profiles/minecraft
[20:04:47] [eventLoopGroupProxy-4-1/INFO] []: java.lang.NoSuchMethodError: com.google.gson.JsonParser.parseString(Ljava/lang/String;)Lcom/google/gson/JsonElement;
[20:04:47] [eventLoopGroupProxy-4-1/INFO] []: 	at io.github.karlatemp.yop.YggdrasilOfficialProxy$main$server$1$1$1$1.invokeSuspend(YggdrasilOfficialProxy.kt:301)
[20:04:47] [eventLoopGroupProxy-4-1/INFO] []: 	at io.github.karlatemp.yop.YggdrasilOfficialProxy$main$server$1$1$1$1.invoke(YggdrasilOfficialProxy.kt)
[20:04:47] [eventLoopGroupProxy-4-1/INFO] []: 	at io.github.karlatemp.yop.YggdrasilOfficialProxy$main$server$1$1$1$1.invoke(YggdrasilOfficialProxy.kt)
[20:04:47] [eventLoopGroupProxy-4-1/INFO] []: 	at io.ktor.util.pipeline.SuspendFunctionGun.loop(SuspendFunctionGun.kt:246)
[20:04:47] [eventLoopGroupProxy-4-1/INFO] []: 	at io.ktor.util.pipeline.SuspendFunctionGun.proceed(SuspendFunctionGun.kt:116)
[20:04:47] [eventLoopGroupProxy-4-1/INFO] []: 	at io.ktor.util.pipeline.SuspendFunctionGun.execute(SuspendFunctionGun.kt:136)
[20:04:47] [eventLoopGroupProxy-4-1/INFO] []: 	at io.ktor.util.pipeline.Pipeline.execute(Pipeline.kt:79)
[20:04:47] [eventLoopGroupProxy-4-1/INFO] []: 	at io.ktor.routing.Routing.executeResult(Routing.kt:155)
[20:04:47] [eventLoopGroupProxy-4-1/INFO] []: 	at io.ktor.routing.Routing.interceptor(Routing.kt:39)
[20:04:47] [eventLoopGroupProxy-4-1/INFO] []: 	at io.ktor.routing.Routing$Feature$install$1.invokeSuspend(Routing.kt:107)
[20:04:47] [eventLoopGroupProxy-4-1/INFO] []: 	at io.ktor.routing.Routing$Feature$install$1.invoke(Routing.kt)
[20:04:47] [eventLoopGroupProxy-4-1/INFO] []: 	at io.ktor.util.pipeline.SuspendFunctionGun.loop(SuspendFunctionGun.kt:246)
[20:04:47] [eventLoopGroupProxy-4-1/INFO] []: 	at io.ktor.util.pipeline.SuspendFunctionGun.proceed(SuspendFunctionGun.kt:116)
[20:04:47] [eventLoopGroupProxy-4-1/INFO] []: 	at io.ktor.util.pipeline.SuspendFunctionGun.execute(SuspendFunctionGun.kt:136)
[20:04:47] [eventLoopGroupProxy-4-1/INFO] []: 	at io.ktor.util.pipeline.Pipeline.execute(Pipeline.kt:79)
[20:04:47] [eventLoopGroupProxy-4-1/INFO] []: 	at io.ktor.server.engine.DefaultEnginePipelineKt$defaultEnginePipeline$2.invokeSuspend(DefaultEnginePipeline.kt:124)
[20:04:47] [eventLoopGroupProxy-4-1/INFO] []: 	at io.ktor.server.engine.DefaultEnginePipelineKt$defaultEnginePipeline$2.invoke(DefaultEnginePipeline.kt)
[20:04:47] [eventLoopGroupProxy-4-1/INFO] []: 	at io.ktor.util.pipeline.SuspendFunctionGun.loop(SuspendFunctionGun.kt:246)
[20:04:47] [eventLoopGroupProxy-4-1/INFO] []: 	at io.ktor.util.pipeline.SuspendFunctionGun.proceed(SuspendFunctionGun.kt:116)
[20:04:47] [eventLoopGroupProxy-4-1/INFO] []: 	at io.ktor.util.pipeline.SuspendFunctionGun.execute(SuspendFunctionGun.kt:136)
[20:04:47] [eventLoopGroupProxy-4-1/INFO] []: 	at io.ktor.util.pipeline.Pipeline.execute(Pipeline.kt:79)
[20:04:47] [eventLoopGroupProxy-4-1/INFO] []: 	at io.ktor.server.netty.NettyApplicationCallHandler$handleRequest$1.invokeSuspend(NettyApplicationCallHandler.kt:123)
[20:04:47] [eventLoopGroupProxy-4-1/INFO] []: 	at io.ktor.server.netty.NettyApplicationCallHandler$handleRequest$1.invoke(NettyApplicationCallHandler.kt)
[20:04:47] [eventLoopGroupProxy-4-1/INFO] []: 	at kotlinx.coroutines.intrinsics.UndispatchedKt.startCoroutineUndispatched(Undispatched.kt:55)
[20:04:47] [eventLoopGroupProxy-4-1/INFO] []: 	at kotlinx.coroutines.CoroutineStart.invoke(CoroutineStart.kt:112)
[20:04:47] [eventLoopGroupProxy-4-1/INFO] []: 	at kotlinx.coroutines.AbstractCoroutine.start(AbstractCoroutine.kt:126)
[20:04:47] [eventLoopGroupProxy-4-1/INFO] []: 	at kotlinx.coroutines.BuildersKt__Builders_commonKt.launch(Builders.common.kt:56)
[20:04:47] [eventLoopGroupProxy-4-1/INFO] []: 	at kotlinx.coroutines.BuildersKt.launch(Unknown Source)
[20:04:47] [eventLoopGroupProxy-4-1/INFO] []: 	at io.ktor.server.netty.NettyApplicationCallHandler.handleRequest(NettyApplicationCallHandler.kt:43)
[20:04:47] [eventLoopGroupProxy-4-1/INFO] []: 	at io.ktor.server.netty.NettyApplicationCallHandler.channelRead(NettyApplicationCallHandler.kt:34)
[20:04:47] [eventLoopGroupProxy-4-1/INFO] []: 	at io.netty.channel.AbstractChannelHandlerContext.invokeChannelRead(AbstractChannelHandlerContext.java:362)
[20:04:47] [eventLoopGroupProxy-4-1/INFO] []: 	at io.netty.channel.AbstractChannelHandlerContext.access$600(AbstractChannelHandlerContext.java:38)
[20:04:47] [eventLoopGroupProxy-4-1/INFO] []: 	at io.netty.channel.AbstractChannelHandlerContext$7.run(AbstractChannelHandlerContext.java:353)
[20:04:47] [eventLoopGroupProxy-4-1/INFO] []: 	at io.netty.util.concurrent.AbstractEventExecutor.safeExecute(AbstractEventExecutor.java:163)
[20:04:47] [eventLoopGroupProxy-4-1/INFO] []: 	at io.netty.util.concurrent.SingleThreadEventExecutor.runAllTasks(SingleThreadEventExecutor.java:404)
[20:04:47] [eventLoopGroupProxy-4-1/INFO] []: 	at io.netty.channel.nio.NioEventLoop.run(NioEventLoop.java:463)
[20:04:47] [eventLoopGroupProxy-4-1/INFO] []: 	at io.netty.util.concurrent.SingleThreadEventExecutor$5.run(SingleThreadEventExecutor.java:884)
[20:04:47] [eventLoopGroupProxy-4-1/INFO] []: 	at io.ktor.server.netty.EventLoopGroupProxy$Companion$create$factory$1$1.run(NettyApplicationEngine.kt:241)
[20:04:47] [eventLoopGroupProxy-4-1/INFO] []: 	at io.netty.util.concurrent.FastThreadLocalRunnable.run(FastThreadLocalRunnable.java:30)
[20:04:47] [eventLoopGroupProxy-4-1/INFO] []: 	at java.lang.Thread.run(Unknown Source)
[20:04:48] [eventLoopGroupProxy-4-1/INFO] []: [YggdrasilOfficialProxy] [ERROR] Unhandled: POST - /api/profiles/minecraft
[20:04:48] [eventLoopGroupProxy-4-1/INFO] []: java.lang.NoSuchMethodError: com.google.gson.JsonParser.parseString(Ljava/lang/String;)Lcom/google/gson/JsonElement;
[20:04:48] [eventLoopGroupProxy-4-1/INFO] []: 	at io.github.karlatemp.yop.YggdrasilOfficialProxy$main$server$1$1$1$1.invokeSuspend(YggdrasilOfficialProxy.kt:301)
[20:04:48] [eventLoopGroupProxy-4-1/INFO] []: 	at io.github.karlatemp.yop.YggdrasilOfficialProxy$main$server$1$1$1$1.invoke(YggdrasilOfficialProxy.kt)
[20:04:48] [eventLoopGroupProxy-4-1/INFO] []: 	at io.github.karlatemp.yop.YggdrasilOfficialProxy$main$server$1$1$1$1.invoke(YggdrasilOfficialProxy.kt)
[20:04:48] [eventLoopGroupProxy-4-1/INFO] []: 	at io.ktor.util.pipeline.SuspendFunctionGun.loop(SuspendFunctionGun.kt:246)
[20:04:48] [eventLoopGroupProxy-4-1/INFO] []: 	at io.ktor.util.pipeline.SuspendFunctionGun.proceed(SuspendFunctionGun.kt:116)
[20:04:48] [eventLoopGroupProxy-4-1/INFO] []: 	at io.ktor.util.pipeline.SuspendFunctionGun.execute(SuspendFunctionGun.kt:136)
[20:04:48] [eventLoopGroupProxy-4-1/INFO] []: 	at io.ktor.util.pipeline.Pipeline.execute(Pipeline.kt:79)
[20:04:48] [eventLoopGroupProxy-4-1/INFO] []: 	at io.ktor.routing.Routing.executeResult(Routing.kt:155)
[20:04:48] [eventLoopGroupProxy-4-1/INFO] []: 	at io.ktor.routing.Routing.interceptor(Routing.kt:39)
[20:04:48] [eventLoopGroupProxy-4-1/INFO] []: 	at io.ktor.routing.Routing$Feature$install$1.invokeSuspend(Routing.kt:107)
[20:04:48] [eventLoopGroupProxy-4-1/INFO] []: 	at io.ktor.routing.Routing$Feature$install$1.invoke(Routing.kt)
[20:04:48] [eventLoopGroupProxy-4-1/INFO] []: 	at io.ktor.util.pipeline.SuspendFunctionGun.loop(SuspendFunctionGun.kt:246)
[20:04:48] [eventLoopGroupProxy-4-1/INFO] []: 	at io.ktor.util.pipeline.SuspendFunctionGun.proceed(SuspendFunctionGun.kt:116)
[20:04:48] [eventLoopGroupProxy-4-1/INFO] []: 	at io.ktor.util.pipeline.SuspendFunctionGun.execute(SuspendFunctionGun.kt:136)
[20:04:48] [eventLoopGroupProxy-4-1/INFO] []: 	at io.ktor.util.pipeline.Pipeline.execute(Pipeline.kt:79)
[20:04:48] [eventLoopGroupProxy-4-1/INFO] []: 	at io.ktor.server.engine.DefaultEnginePipelineKt$defaultEnginePipeline$2.invokeSuspend(DefaultEnginePipeline.kt:124)
[20:04:48] [eventLoopGroupProxy-4-1/INFO] []: 	at io.ktor.server.engine.DefaultEnginePipelineKt$defaultEnginePipeline$2.invoke(DefaultEnginePipeline.kt)
[20:04:48] [eventLoopGroupProxy-4-1/INFO] []: 	at io.ktor.util.pipeline.SuspendFunctionGun.loop(SuspendFunctionGun.kt:246)
[20:04:48] [eventLoopGroupProxy-4-1/INFO] []: 	at io.ktor.util.pipeline.SuspendFunctionGun.proceed(SuspendFunctionGun.kt:116)
[20:04:48] [eventLoopGroupProxy-4-1/INFO] []: 	at io.ktor.util.pipeline.SuspendFunctionGun.execute(SuspendFunctionGun.kt:136)
[20:04:48] [eventLoopGroupProxy-4-1/INFO] []: 	at io.ktor.util.pipeline.Pipeline.execute(Pipeline.kt:79)
[20:04:48] [eventLoopGroupProxy-4-1/INFO] []: 	at io.ktor.server.netty.NettyApplicationCallHandler$handleRequest$1.invokeSuspend(NettyApplicationCallHandler.kt:123)
[20:04:48] [eventLoopGroupProxy-4-1/INFO] []: 	at io.ktor.server.netty.NettyApplicationCallHandler$handleRequest$1.invoke(NettyApplicationCallHandler.kt)
[20:04:48] [eventLoopGroupProxy-4-1/INFO] []: 	at kotlinx.coroutines.intrinsics.UndispatchedKt.startCoroutineUndispatched(Undispatched.kt:55)
[20:04:48] [eventLoopGroupProxy-4-1/INFO] []: 	at kotlinx.coroutines.CoroutineStart.invoke(CoroutineStart.kt:112)
[20:04:48] [eventLoopGroupProxy-4-1/INFO] []: 	at kotlinx.coroutines.AbstractCoroutine.start(AbstractCoroutine.kt:126)
[20:04:48] [eventLoopGroupProxy-4-1/INFO] []: 	at kotlinx.coroutines.BuildersKt__Builders_commonKt.launch(Builders.common.kt:56)
[20:04:48] [eventLoopGroupProxy-4-1/INFO] []: 	at kotlinx.coroutines.BuildersKt.launch(Unknown Source)
[20:04:48] [eventLoopGroupProxy-4-1/INFO] []: 	at io.ktor.server.netty.NettyApplicationCallHandler.handleRequest(NettyApplicationCallHandler.kt:43)
[20:04:48] [eventLoopGroupProxy-4-1/INFO] []: 	at io.ktor.server.netty.NettyApplicationCallHandler.channelRead(NettyApplicationCallHandler.kt:34)
[20:04:48] [eventLoopGroupProxy-4-1/INFO] []: 	at io.netty.channel.AbstractChannelHandlerContext.invokeChannelRead(AbstractChannelHandlerContext.java:362)
[20:04:48] [eventLoopGroupProxy-4-1/INFO] []: 	at io.netty.channel.AbstractChannelHandlerContext.access$600(AbstractChannelHandlerContext.java:38)
[20:0`

**Comment by Karlatemp** [comment]
参考 https://github.com/YggdrasilOfficialProxy/YggdrasilOfficialProxy#standard-proxy-server-setup
