### ISSUE TITLE
无法使用-javaagent方式启动

### ISSUE THREAD

**Issue by 10935336** [YggdrasilOfficialProxy/YggdrasilOfficialProxy#5]
是我哪里姿势不对吗

这样可以正常启动
`java -jar YggdrasilOfficialProxy.jar`
```
############################
# Yggdrasil Official Proxy #
# Copyright (c) Karlatemp  #
#     2018-2020.           #
# All rights reserved.     #
############################

```

这样不行
`java -Xmx10G -javaagent:YggdrasilOfficialProxy.jar -jar forge-1.7.10-10.13.4.1614-1.7.10-universal.jar nogui`
```

Exception in thread "main" java.lang.reflect.InvocationTargetException
        at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
        at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
        at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
        at java.lang.reflect.Method.invoke(Method.java:498)
        at sun.instrument.InstrumentationImpl.loadClassAndStartAgent(InstrumentationImpl.java:386)
        at sun.instrument.InstrumentationImpl.loadClassAndCallPremain(InstrumentationImpl.java:401)
Caused by: java.lang.NoSuchMethodError: io.netty.util.AttributeKey.newInstance(Ljava/lang/String;)Lio/netty/util/AttributeKey;
        at cn.mcres.karlatemp.yop.server.ContextHandler.<clinit>(ContextHandler.java:38)
        at cn.mcres.karlatemp.yop.server.api.users.Minecraft.register(Minecraft.java:95)
        at cn.mcres.karlatemp.yop.ConfigSetup.init(ConfigSetup.java:65)
        at cn.mcres.karlatemp.yop.YggdrasilOfficialProxy.startup(YggdrasilOfficialProxy.java:38)
        at cn.mcres.karlatemp.yop.YggdrasilOfficialProxy.premain(YggdrasilOfficialProxy.java:119)
        ... 6 more
FATAL ERROR in native method: processing of -javaagent failed
已放弃(吐核)

```

**Comment by Karlatemp** [comment]
服务端版本的netty版本过旧，请使用外部服务器的方法挂载yop

**Comment by 10935336** [comment]
好的，感谢
