### ISSUE TITLE
Relocate 

### ISSUE THREAD

**Issue by Ghost-chu** [YggdrasilOfficialProxy/YggdrasilOfficialProxy#6]
将依赖relocate位置，避免和服务端核心自带依赖冲突
```
oke(NativeMethodAccessorImpl.java:62)
[01:07:46 INFO]: [STDERR]:  at java.base/jdk.internal.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
[01:07:46 INFO]: [STDERR]:  at java.base/java.lang.reflect.Method.invoke(Method.java:566)
[01:07:46 INFO]: [STDERR]:  at io.papermc.paperclip.Paperclip.main(Paperclip.java:54)
[MCSMANAGER] -------------------------------------------------------------- 
[MCSMANAGER] [ 2020/7/4 1:7:52 ]: 服务端 SunnySide 执行开启命令. 
[MCSMANAGER] -------------------------------------------------------------- 
############################
# Yggdrasil Official Proxy #
# Copyright (c) Karlatemp  #
#     2018-2020.           #
# All rights reserved.     #
############################
#            Version: 1.0.0
#    Java    Version: 11.0.7
#    Server Port    : 42285
# Configuration Path: /home/gamerteam/server/share/YggdrasilOfficialProxy.yml
# Yggdrasil API ROOT: https://user.mcxk.net/api/yggdrasil/
#     First Connect : Yggdrasil
# Proxy of Official : DIRECT
# Proxy of Yggdrasil: DIRECT
# Connect Timed out : 60000
# Reading Timed out : 60000
# Yggdrasil-Fix: true
############################
# Server started.
# Injector path: /home/gamerteam/server/share/authlib-injector-1.1.29.jar
# Injector argument: http://localhost:42285
[authlib-injector.launch] [INFO] Version: 1.1.29
[authlib-injector.config] [INFO] API root: http://localhost:42285/
[authlib-injector.config] [WARNING] You are using HTTP protocol, which is INSECURE! Please switch to HTTPS if possible.
>System Info: Java 11 (Java HotSpot(TM) 64-Bit Server VM 11.0.7+8-LTS) Host: Linux 5.6.14-1.el7.elrepo.x86_64 (amd64)
Loading libraries, please wait...
2020-08-06 01:07:55,887 main WARN Advanced terminal features are not available in this environment
[01:08:01 INFO]: [STDERR]: java.lang.NoSuchMethodError: org.yaml.snakeyaml.LoaderOptions.setMaxAliasesForCollections(I)V
[01:08:01 INFO]: [STDERR]:  at org.bukkit.configuration.file.YamlConfiguration.loadFromString(YamlConfiguration.java:56)
[01:08:01 INFO]: [STDERR]:  at org.bukkit.configuration.file.FileConfiguration.load(FileConfiguration.java:160)
[01:08:01 INFO]: [STDERR]:  at org.bukkit.configuration.file.FileConfiguration.load(FileConfiguration.java:128)
[01:08:01 INFO]: [STDERR]:  at net.minecraft.server.v1_16_R1.Main.loadConfigFile(Main.java:230)
[01:08:01 INFO]: [STDERR]:  at net.minecraft.server.v1_16_R1.Main.main(Main.java:68)
[01:08:01 INFO]: [STDERR]:  at org.bukkit.craftbukkit.Main.main(Main.java:276)
[01:08:01 INFO]: [STDERR]:  at java.base/jdk.internal.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
[01:08:01 INFO]: [STDERR]:  at java.base/jdk.internal.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
[01:08:01 INFO]: [STDERR]:  at java.base/jdk.internal.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
[01:08:01 INFO]: [STDERR]:  at java.base/java.lang.reflect.Method.invoke(Method.java:566)
[01:08:01 INFO]: [STDERR]:  at io.papermc.paperclip.Paperclip.main(Paperclip.java:54)
```

**Comment by Karlatemp** [comment]
[v2.0.0](https://github.com/Karlatemp/YggdrasilOfficialProxy/releases/tag/v2.0.0), 配置有变化, 请重新配置, 详细配置请参考 README.MD

**Comment by Ghost-chu** [comment]
已经自己修好了
拿7z把服务端的依赖拖了进去覆盖

---Original---
